language: node_js

node_js:
  - node
cache:
  directories:
    - "node_modules"
    
install:
    - npm install
    - npm ci
services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres
  
script:
  - npm run lint:fix
  - npm run test:coveralls